# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

java_version = 21
modid=preview_placement
mod_version = 26.1.0.0-alpha
neo_version = 26.1.0.0-alpha.1+snapshot-1
